server:
  port: 8081



spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://59.13.200.90:5532/airbnbapi
    username: ENC(lOMQCUPklqT/UWHmMWQ7tA==)
    password: ENC(ezP27P4Yq8Q73O3RXHWNEQ==)

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  jwt:
    secret-key: ENC(1E5D9LTH/t4Fkl9AB2ufV72DcA8S8pIvAVcW2c4pJgvqVwQIvBTdawbsKXXAbbo2YvNePLX/IOIusGgDj7zXdrR5/G/0z1YKhmwaJyYO1HE=)
    expiration: 86400000
    refresh-token:
      expiration: 604800000 # 7 day

  servlet:
    multipart:
      max-request-size: 10MB
      enabled: true
      max-file-size: 10MB
      location: C:\\Users\\SUN\\work\\airbnb-react-spring\\ui\\public\\images\\listing


  mail:
    host: smtp.gmail.com
    port: 587
    username: syseoz@gmail.com
    password: ENC(NdwLGJAB+YhsvsL2/EZwGYaVlchcMYcGJR80vb6mMpg=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

airbnb.upload.path: C:\\Users\\SUN\\work\\airbnb-react-spring\\ui\\public\\images\\listing

mybatis:
  mapper-locations: mybatis/mapper/**.xml

logging:
  level:
    com.example.airbnbApi: debug
    org.hibernate.sql: debug




jasypt:
  encryptor:
    bean: jasyptStringEncryptor